# Generated by Django 5.1.7 on 2025-05-27 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home', '홈'), ('review', '후기'), ('question', '궁금해'), ('share', '자료공유'), ('chat', '잡담')], default='home', max_length=20)),
                ('subcategory', models.CharField(blank=True, choices=[('review', [('home', '홈'), ('life', '인생'), ('living', '자취'), ('univ', '대학'), ('money', '지갑'), ('sport', '운동'), ('love', '연애'), ('comp', '직장')]), ('question', [('home', '홈'), ('life', '인생'), ('living', '자취'), ('univ', '대학'), ('money', '지갑'), ('sport', '운동'), ('love', '연애'), ('comp', '직장')]), ('share', [('home', '홈'), ('life', '인생'), ('living', '자취'), ('univ', '대학'), ('money', '지갑'), ('sport', '운동'), ('love', '연애'), ('comp', '직장')]), ('chat', [('home', '홈'), ('life', '인생'), ('living', '자취'), ('univ', '대학'), ('money', '지갑'), ('sport', '운동'), ('love', '연애'), ('comp', '직장')])], max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.post')),
            ],
        ),
    ]
