# Generated by Django 5.2.1 on 2025-05-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('home', '홈'), ('review', '후기'), ('question', '궁금해'), ('share', '자료공유'), ('chat', '잡담')], default='home', max_length=20),
        ),
    ]
