# Generated by Django 5.2.1 on 2025-05-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('review', [('home', '홈'), ('life', '인생'), ('living', '자취'), ('univ', '대학'), ('money', '지갑'), ('sport', '운동'), ('love', '연애'), ('comp', '직장')]), ('question', [('home', '홈'), ('life', '인생'), ('living', '자취'), ('univ', '대학'), ('money', '지갑'), ('sport', '운동'), ('love', '연애'), ('comp', '직장')]), ('share', [('home', '홈'), ('life', '인생'), ('living', '자취'), ('univ', '대학'), ('money', '지갑'), ('sport', '운동'), ('love', '연애'), ('comp', '직장')]), ('chat', [('home', '홈'), ('life', '인생'), ('living', '자취'), ('univ', '대학'), ('money', '지갑'), ('sport', '운동'), ('love', '연애'), ('comp', '직장')])], max_length=20, null=True),
        ),
    ]
